dist: xenial
language: cpp

addons:
  apt:
    sources:
     - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
       key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
     - ninja-build
     - llvm-dev
     - libclang-dev
     - clang
     - gcc-9

before_install:
 # Install a supported cmake version (>= 3.4.3)
 - wget -O cmake.sh https://cmake.org/files/v3.16/cmake-3.16.4-Linux-x86_64.sh
 - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
 
 - GCC_PATH=`which gcc-9`
 - GPP_PATH=`which g++-9`
 - CLANG_PATH=`which clang-10.0`
 - CLANG_PP_PATH=`which clang++-10.0`

script:
 - mkdir cmake-build-gcc-debug
 - cd cmake-build-gcc-debug
 - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=$GCC_PATH -DCMAKE_CXX_COMPILER=$GPP_PATH ../
 - make
 - make test
